# Generated by Django 5.0.4 on 2024-05-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uapcanteen', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lunch',
        ),
    ]
