# Generated by Django 5.0.4 on 2024-05-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapcanteen', '0008_cart_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.breakfast'),
        ),
    ]
